Handle ConnectionRefusedError in vCenter query error handler
If we received an error from the vCenter, it can happen that we can't
destroy the view we created, because the vCenter became unavailable. We
should not stop the process but instead try to reconnect on the next query.
This fixes:

  Traceback (most recent call last):
    File "/usr/local/bin/vcenter-operator", line 10, in <module>
      sys.exit(main())
    File "/usr/src/app/vcenter_operator/cmd.py", line 70, in main
      configurator.poll()
    File "/usr/src/app/vcenter_operator/configurator.py", line 354, in poll
      hosts[host] = self._poll(host)
    File "/usr/src/app/vcenter_operator/configurator.py", line 259, in _poll
      self._add_code('vcenter_datacenter', cluster_options)
    File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/src/app/vcenter_operator/configurator.py", line 50, in filter_spec_context
      view_ref.DestroyView()
    File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
      self.f(*(self.args + (obj,) + args), **kwargs)
    File "/usr/local/lib/python3.8/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
      return self._stub.InvokeMethod(self, info, args)
    File "/usr/local/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1350, in InvokeMethod
      conn.request('POST', self.path, req, headers)
    File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
      self.send(msg)
    File "/usr/local/lib/python3.8/http/client.py", line 950, in send
      self.connect()
    File "/usr/local/lib/python3.8/site-packages/pyVmomi/SoapAdapter.py", line 1039, in connect
      http_client.HTTPSConnection.connect(self)
    File "/usr/local/lib/python3.8/http/client.py", line 1417, in connect
      super().connect()
    File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
      self.sock = self._create_connection(
    File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
      raise err
    File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
      sock.connect(sa)
  ConnectionRefusedError: [Errno 111] Connection refuse