Prohibit UnboundLocalError in filter_spec_context()
When entering the `finally` clause in
`configurator.filter_spec_context()`, we might have errored out without
defining the local variable `view_ref`, which leads to an exception
	UnboundLocalError: local variable 'view_ref' referenced before assignment

With defining the variable up front, we can safely check if we need to
act in the `finally` clause.