Switch to kubernetes<13
We're on k8s 1.15 everywhere and 12 is the release for 1.16, but still
supports 1.15 according to the compatibility matrix in [0].

We need to switch, even though things worked until now, because a new
region is already on 1.20 and there, we cannot create CRDs anymore:

	Traceback (most recent call last):
	  File "/usr/local/bin/vcenter-operator", line 10, in <module>
		sys.exit(main())
	  File "/usr/src/app/vcenter_operator/cmd.py", line 70, in main
		configurator.poll()
	  File "/usr/src/app/vcenter_operator/configurator.py", line 371, in poll
		self._add_code('vcenter_global', all_values)
	  File "/usr/src/app/vcenter_operator/configurator.py", line 269, in _add_code
		template_names = env.list_templates(
	  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 810, in list_templates
		names = self.loader.list_templates()
	  File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 434, in list_templates
		found.update(loader.list_templates())
	  File "/usr/src/app/vcenter_operator/templates.py", line 149, in list_templates
		self.poll_crds()
	  File "/usr/src/app/vcenter_operator/templates.py", line 164, in poll_crds
		self._create_custom_resource_definitions()
	  File "/usr/src/app/vcenter_operator/templates.py", line 239, in _create_custom_resource_definitions
		api.create_custom_resource_definition(self._crd)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 57, in create_custom_resource_definition
		(data) = self.create_custom_resource_definition_with_http_info(body, **kwargs)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 123, in create_custom_resource_definition_with_http_info
		return self.api_client.call_api('/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions', 'POST',
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 317, in call_api
		return self.__call_api(resource_path, method,
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
		return_data = self.deserialize(response_data, response_type)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
		return self.__deserialize(data, response_type)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
		return self.__deserialize_model(data, klass)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
		kwargs[attr] = self.__deserialize(value, attr_type)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
		return self.__deserialize_model(data, klass)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
		instance = klass(**kwargs)
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/models/v1beta1_custom_resource_definition_status.py", line 53, in __init__
		self.conditions = conditions
	  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/models/v1beta1_custom_resource_definition_status.py", line 101, in conditions
		raise ValueError("Invalid value for `conditions`, must not be `None`")
	ValueError: Invalid value for `conditions`, must not be `None`

Searching for this error, [1] suggests that release 12 of the
kubernetes python client has a fix for it.

[0] https://github.com/kubernetes-client/python#compatibility
[1] https://github.com/kubernetes-client/python/issues/1022