Fix crash on fetching new SOA serial
The vcenter-operator recently stopped working, because it couldn't
connect to DNS to retrieve the new SOA serial. We now handle that case
gracefully an just retry in the next loop's discovery.
Additionally, we also print a warning message if we couldn't find a
SOA serial.

	Traceback (most recent call last):
	  File "/usr/local/bin/vcenter-operator", line 10, in <module>
		sys.exit(main())
	  File "/usr/src/app/vcenter_operator/cmd.py", line 69, in main
		discovery.discover()
	  File "/usr/src/app/vcenter_operator/discovery.py", line 72, in discover
		new_serial = self.remote_soa_serial()
	  File "/usr/src/app/vcenter_operator/discovery.py", line 62, in remote_soa_serial
		for message in xfr(self.ip, self.domain, port=self.port,
	  File "/usr/local/lib/python3.8/site-packages/dns/query.py", line 926, in xfr
		_connect(s, destination, expiration)
	  File "/usr/local/lib/python3.8/site-packages/dns/query.py", line 704, in _connect
		raise OSError(err, os.strerror(err))
	ConnectionRefusedError: [Errno 111] Connection refused